# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Run application tests

on:
  push:
    branches: [ main, feat/auth ]
  pull_request:
    branches: [ main ]

jobs:
  run-tests:

    name: Run all tests with pytest
    runs-on: ubuntu-latest
    env:
        DB_PASSWORD: supersecure
        DB_USER: tester
        DB_DATABASE: charlotte_test

    steps:
    - uses: actions/checkout@v2
    - name: Start up test database 
      run: docker-compose up -d db 
    - name: Install dependencies
      run: |
        pip install pipenv
        pipenv install --system
    - name: Test with pytest
      run: pytest -v
    